name: Discord Gaming RSS

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run RSS to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python rss_to_discord.py

      - name: Save posted cache
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add posted.json
          git commit -m "Update posted cache" || echo "No changes"
          git push
